version: '3.7'

services:
  shipmentbyco:
    build:
      context: ./shippingbyco
    volumes:
      - app_build:/app/build
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - app_build:/var/www/app
    depends_on:
      - shipmentbyco
volumes:
  app_build:
  